# nixpacks.lock.toml — использовать, если в репо добавлен package-lock.json
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --include=dev --no-audit --no-fund"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start"
