/* path: lib/strings.ts */
import type { Locale } from './i18n';

type Dict = Record<string, string>;
const D = (d: Dict) => d;

export const STRINGS: Record<Locale, Dict> = {
  ru: D({
    brand: 'LiveManager',
    tagline: 'Умные инструменты на каждый день',
    cabinet: 'Личный кабинет',
    buy: 'Купить подписку',
    tasks: 'Ежедневные задачи',
    expert: 'Эксперт центр',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'Сменить язык/страну',
    chooseLang: 'Выберите язык интерфейса',
    save: 'Сохранить',
    cancel: 'Отмена',
  }),

  en: D({
    brand: 'LiveManager',
    tagline: 'Smart tools for every day',
    cabinet: 'Account',
    buy: 'Buy subscription',
    tasks: 'Daily tasks',
    expert: 'Expert center',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'Change language/country',
    chooseLang: 'Choose interface language',
    save: 'Save',
    cancel: 'Cancel',
  }),

  uk: D({
    brand: 'LiveManager',
    tagline: 'Розумні інструменти на кожен день',
    cabinet: 'Обліковий запис',
    buy: 'Купити підписку',
    tasks: 'Щоденні завдання',
    expert: 'Експерт-центр',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'Змінити мову/країну',
    chooseLang: 'Оберіть мову інтерфейсу',
    save: 'Зберегти',
    cancel: 'Скасувати',
  }),

  be: D({
    brand: 'LiveManager',
    tagline: 'Разумныя інструменты на кожны дзень',
    cabinet: 'Асабісты кабінет',
    buy: 'Купіць падпіску',
    tasks: 'Штодзённыя задачы',
    expert: 'Эксперт-цэнтр',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'Змяніць мову/краіну',
    chooseLang: 'Абраць мову інтэрфейсу',
    save: 'Захаваць',
    cancel: 'Адмяніць',
  }),

  kk: D({
    brand: 'LiveManager',
    tagline: 'Күн сайынғы ақылды құралдар',
    cabinet: 'Жеке кабинет',
    buy: 'Жазылым сатып алу',
    tasks: 'Күнделікті тапсырмалар',
    expert: 'Сарапшылар орталығы',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'Тілді/елді өзгерту',
    chooseLang: 'Интерфейс тілін таңдаңыз',
    save: 'Сақтау',
    cancel: 'Болдырмау',
  }),

  uz: D({
    brand: 'LiveManager',
    tagline: 'Har kuni uchun aqlli vositalar',
    cabinet: 'Shaxsiy kabinet',
    buy: 'Obunani sotib olish',
    tasks: 'Kundalik vazifalar',
    expert: 'Ekspert markazi',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'Tilni/mamlakatni o‘zgartirish',
    chooseLang: 'Interfeys tilini tanlang',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
  }),

  ky: D({
    brand: 'LiveManager',
    tagline: 'Күн сайынгы акылдуу куралдар',
    cabinet: 'Жеке кабинет',
    buy: 'Жазылууну сатып алуу',
    tasks: 'Күнүмдүк тапшырмалар',
    expert: 'Эксперт борбору',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'Тилди/мамлекетті өзгөртүү',
    chooseLang: 'Интерфейстин тилин тандаңыз',
    save: 'Сактоо',
    cancel: 'Жокко чыгаруу',
  }),

  fa: D({
    brand: 'LiveManager',
    tagline: 'ابزارهای هوشمند برای هر روز',
    cabinet: 'حساب کاربری',
    buy: 'خرید اشتراک',
    tasks: 'وظایف روزانه',
    expert: 'مرکز کارشناسان',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'تغییر زبان/کشور',
    chooseLang: 'زبان رابط را انتخاب کنید',
    save: 'ذخیره',
    cancel: 'انصراف',
  }),

  hi: D({
    brand: 'LiveManager',
    tagline: 'हर दिन के लिए स्मार्ट टूल',
    cabinet: 'खाता',
    buy: 'सदस्यता खरीदें',
    tasks: 'दैनिक कार्य',
    expert: 'एक्सपर्ट सेंटर',
    pro: 'Pro',
    proPlus: 'Pro+',
    langBtn: 'भाषा/देश बदलें',
    chooseLang: 'इंटरफ़ेस भाषा चुनें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
  }),
};

export const t = (locale: Locale, key: string, fallback?: string) =>
  STRINGS[locale]?.[key] ?? STRINGS.ru[key] ?? fallback ?? key;
